// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VClinic.Infrastructure.Persistence;

#nullable disable

namespace VClinic.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251225054839_SyncMedicoEspecialidadHorario")]
    partial class SyncMedicoEspecialidadHorario
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Medico", b =>
                {
                    b.Property<long>("IdMedico")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("IdMedico"));

                    b.Property<string>("Especialidad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EstaActivo")
                        .HasColumnType("bit");

                    b.Property<string>("Horario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("IdPersona")
                        .HasColumnType("bigint");

                    b.Property<string>("NumeroColegiado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("IdMedico");

                    b.HasIndex("IdPersona")
                        .IsUnique();

                    b.HasIndex("NumeroColegiado")
                        .IsUnique();

                    b.ToTable("Medicos", (string)null);
                });

            modelBuilder.Entity("VClinic.Domain.Entities.Catalogos.Departamento", b =>
                {
                    b.Property<int>("IdDepartamento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDepartamento"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<bool>("EstaActivo")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdDepartamento");

                    b.ToTable("Departamentos", (string)null);
                });

            modelBuilder.Entity("VClinic.Domain.Entities.Catalogos.EstadoCivil", b =>
                {
                    b.Property<int>("IdEstadoCivil")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEstadoCivil"));

                    b.Property<bool>("EstaActivo")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("IdEstadoCivil");

                    b.ToTable("EstadoCivil", (string)null);
                });

            modelBuilder.Entity("VClinic.Domain.Entities.Catalogos.Genero", b =>
                {
                    b.Property<int>("IdGenero")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdGenero"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<bool>("EstaActivo")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("IdGenero");

                    b.ToTable("Generos");
                });

            modelBuilder.Entity("VClinic.Domain.Entities.Catalogos.GrupoSanguinio", b =>
                {
                    b.Property<int>("IdGrupoSangre")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdGrupoSangre"));

                    b.Property<bool>("EstaActivo")
                        .HasColumnType("bit");

                    b.Property<string>("FactorRH")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("GrupoABO")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("TipoSangre")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.HasKey("IdGrupoSangre");

                    b.ToTable("GrupoSangre", (string)null);
                });

            modelBuilder.Entity("VClinic.Domain.Entities.Catalogos.Ocupacion", b =>
                {
                    b.Property<int>("IdOcupacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdOcupacion"));

                    b.Property<bool>("EstaActivo")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.HasKey("IdOcupacion");

                    b.ToTable("Ocupacions");
                });

            modelBuilder.Entity("VClinic.Domain.Entities.Catalogos.Posiciones", b =>
                {
                    b.Property<int>("IdPosicion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPosicion"));

                    b.Property<bool>("EstaActivo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int>("Nivel")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("IdPosicion");

                    b.ToTable("Posiciones");
                });

            modelBuilder.Entity("VClinic.Domain.Entities.Catalogos.Profesion", b =>
                {
                    b.Property<int>("IdProfesion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdProfesion"));

                    b.Property<bool>("EstaActivo")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdProfesion");

                    b.ToTable("Profesion", (string)null);
                });

            modelBuilder.Entity("VClinic.Domain.Entities.Catalogos.TipoEquipamento", b =>
                {
                    b.Property<int>("IdTipoEquipamento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTipoEquipamento"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("EstaActivo")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("IdTipoEquipamento");

                    b.ToTable("TipoEquipamento", (string)null);
                });

            modelBuilder.Entity("VClinic.Domain.Entities.Catalogos.TipoIdentificacion", b =>
                {
                    b.Property<int>("IdTipoIdentificacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTipoIdentificacion"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<bool>("EstaActivo")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("IdTipoIdentificacion");

                    b.ToTable("TipoIdentificacion", (string)null);
                });

            modelBuilder.Entity("VClinic.Domain.Entities.CentroMedico", b =>
                {
                    b.Property<int>("IdCentroMedico")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCentroMedico"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("EstaActivo")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaFundacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Rnc")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.HasKey("IdCentroMedico");

                    b.ToTable("CentrosMedicos", (string)null);
                });

            modelBuilder.Entity("VClinic.Domain.Entities.DatosPersona", b =>
                {
                    b.Property<long>("IdPersona")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("IdPersona"));

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Celular")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Direccion")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("FechaNacimiento")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdEstadoCivil")
                        .HasColumnType("int");

                    b.Property<int>("IdGenero")
                        .HasColumnType("int");

                    b.Property<int>("IdTipoIdentificacion")
                        .HasColumnType("int");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NumeroIdentificacion")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("IdPersona");

                    b.HasIndex("IdEstadoCivil");

                    b.HasIndex("IdGenero");

                    b.HasIndex("IdTipoIdentificacion", "NumeroIdentificacion")
                        .IsUnique();

                    b.ToTable("Personas", (string)null);
                });

            modelBuilder.Entity("VClinic.Domain.Entities.Empleado", b =>
                {
                    b.Property<long>("IdEmpleado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("IdEmpleado"));

                    b.Property<string>("CodigoEmpleado")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<bool>("EstaActivo")
                        .HasColumnType("bit");

                    b.Property<int>("IdDepartamento")
                        .HasColumnType("int");

                    b.Property<long>("IdPersona")
                        .HasColumnType("bigint");

                    b.Property<int>("IdPosicion")
                        .HasColumnType("int");

                    b.Property<int>("IdProfesion")
                        .HasColumnType("int");

                    b.HasKey("IdEmpleado");

                    b.HasIndex("CodigoEmpleado")
                        .IsUnique();

                    b.HasIndex("IdDepartamento");

                    b.HasIndex("IdPersona")
                        .IsUnique();

                    b.HasIndex("IdPosicion");

                    b.HasIndex("IdProfesion");

                    b.ToTable("Empleados", (string)null);
                });

            modelBuilder.Entity("VClinic.Domain.Entities.Equipamento", b =>
                {
                    b.Property<int>("IdEquipamento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEquipamento"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("EstaActivo")
                        .HasColumnType("bit");

                    b.Property<int>("IdTipoEquipo")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(35)
                        .HasColumnType("nvarchar(35)");

                    b.HasKey("IdEquipamento");

                    b.ToTable("Equipamento", (string)null);
                });

            modelBuilder.Entity("VClinic.Domain.Entities.Paciente", b =>
                {
                    b.Property<long>("IdPaciente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("IdPaciente"));

                    b.Property<bool>("EstaActivo")
                        .HasColumnType("bit");

                    b.Property<int>("GrupoSanguinioIdGrupoSangre")
                        .HasColumnType("int");

                    b.Property<int>("IdGrupoSangre")
                        .HasColumnType("int");

                    b.Property<int>("IdHistorial")
                        .HasColumnType("int");

                    b.Property<int>("IdOcupacion")
                        .HasColumnType("int");

                    b.Property<long>("IdPersona")
                        .HasColumnType("bigint");

                    b.Property<int>("OcupacionIdOcupacion")
                        .HasColumnType("int");

                    b.HasKey("IdPaciente");

                    b.HasIndex("GrupoSanguinioIdGrupoSangre");

                    b.HasIndex("IdHistorial")
                        .IsUnique();

                    b.HasIndex("IdPersona")
                        .IsUnique();

                    b.HasIndex("OcupacionIdOcupacion");

                    b.ToTable("Pacientes", (string)null);
                });

            modelBuilder.Entity("Medico", b =>
                {
                    b.HasOne("VClinic.Domain.Entities.DatosPersona", "Persona")
                        .WithOne("Medico")
                        .HasForeignKey("Medico", "IdPersona")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Persona");
                });

            modelBuilder.Entity("VClinic.Domain.Entities.DatosPersona", b =>
                {
                    b.HasOne("VClinic.Domain.Entities.Catalogos.EstadoCivil", "EstadoCivil")
                        .WithMany("Personas")
                        .HasForeignKey("IdEstadoCivil")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VClinic.Domain.Entities.Catalogos.Genero", "Genero")
                        .WithMany("Personas")
                        .HasForeignKey("IdGenero")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VClinic.Domain.Entities.Catalogos.TipoIdentificacion", "TipoIdentificacion")
                        .WithMany("Personas")
                        .HasForeignKey("IdTipoIdentificacion")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("EstadoCivil");

                    b.Navigation("Genero");

                    b.Navigation("TipoIdentificacion");
                });

            modelBuilder.Entity("VClinic.Domain.Entities.Empleado", b =>
                {
                    b.HasOne("VClinic.Domain.Entities.Catalogos.Departamento", "Departamento")
                        .WithMany("Empleados")
                        .HasForeignKey("IdDepartamento")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VClinic.Domain.Entities.DatosPersona", "Persona")
                        .WithOne("Empleado")
                        .HasForeignKey("VClinic.Domain.Entities.Empleado", "IdPersona")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VClinic.Domain.Entities.Catalogos.Posiciones", "Posiciones")
                        .WithMany("Empleados")
                        .HasForeignKey("IdPosicion")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VClinic.Domain.Entities.Catalogos.Profesion", "Profesion")
                        .WithMany("Empleados")
                        .HasForeignKey("IdProfesion")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Departamento");

                    b.Navigation("Persona");

                    b.Navigation("Posiciones");

                    b.Navigation("Profesion");
                });

            modelBuilder.Entity("VClinic.Domain.Entities.Paciente", b =>
                {
                    b.HasOne("VClinic.Domain.Entities.Catalogos.GrupoSanguinio", "GrupoSanguinio")
                        .WithMany("Pacientes")
                        .HasForeignKey("GrupoSanguinioIdGrupoSangre")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VClinic.Domain.Entities.DatosPersona", "Persona")
                        .WithOne("Paciente")
                        .HasForeignKey("VClinic.Domain.Entities.Paciente", "IdPersona")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VClinic.Domain.Entities.Catalogos.Ocupacion", "Ocupacion")
                        .WithMany("Pacientes")
                        .HasForeignKey("OcupacionIdOcupacion")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GrupoSanguinio");

                    b.Navigation("Ocupacion");

                    b.Navigation("Persona");
                });

            modelBuilder.Entity("VClinic.Domain.Entities.Catalogos.Departamento", b =>
                {
                    b.Navigation("Empleados");
                });

            modelBuilder.Entity("VClinic.Domain.Entities.Catalogos.EstadoCivil", b =>
                {
                    b.Navigation("Personas");
                });

            modelBuilder.Entity("VClinic.Domain.Entities.Catalogos.Genero", b =>
                {
                    b.Navigation("Personas");
                });

            modelBuilder.Entity("VClinic.Domain.Entities.Catalogos.GrupoSanguinio", b =>
                {
                    b.Navigation("Pacientes");
                });

            modelBuilder.Entity("VClinic.Domain.Entities.Catalogos.Ocupacion", b =>
                {
                    b.Navigation("Pacientes");
                });

            modelBuilder.Entity("VClinic.Domain.Entities.Catalogos.Posiciones", b =>
                {
                    b.Navigation("Empleados");
                });

            modelBuilder.Entity("VClinic.Domain.Entities.Catalogos.Profesion", b =>
                {
                    b.Navigation("Empleados");
                });

            modelBuilder.Entity("VClinic.Domain.Entities.Catalogos.TipoIdentificacion", b =>
                {
                    b.Navigation("Personas");
                });

            modelBuilder.Entity("VClinic.Domain.Entities.DatosPersona", b =>
                {
                    b.Navigation("Empleado");

                    b.Navigation("Medico");

                    b.Navigation("Paciente");
                });
#pragma warning restore 612, 618
        }
    }
}
